# **Jour 3 —  Librairie - NumPy**


![](https://images.unsplash.com/photo-1476525223214-c31ff100e1ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80)
Picture by [Jason Briscoe](https://unsplash.com/photos/HN_4K2diUWs)

Il s'agit d'un exercice où vous devrez passer un peu de temps à explorer la documentation de [NumPy documentation](https://numpy.org/doc/1.18/).

Pour installer numpy utilisez la commande suivante dans votre terminal :
`pip install numpy`

Sur macOS :
`pip3 install numpy`



Pour vous aider à réaliser ce TD, consultez et utilisez les fonctions suivantes :
- `import numpy as np`  : Pour importer la biblothèque numpy,
- `np.array([i1,i2,i3])` : Pour créer un vecteur contenant les éléments i1, i2 et i3,
- `np.zeros(n)`  : Pour créer un vecteur de taille n contenant que des 0,
- `v[i]` : Pour obtenir la valeur à l'index i du vecteur v,
- `np.random.randint(n, m, k)` : Pour créer des vecteurs de taille k ayant des valeurs aléatoires comprises entre n à m,
- `np.arange(n,m)`  :  Pour créer des vecteurs ayant des valeurs de n à m,
- `v.argmax()` : Pour trouver l'indice de la valeur maximale,
- `v[i]` : Pour obtenir la valeur à l'index i du vecteur v,
- `np.nonzero(n)`  : Pour créer des vecteurs de taille n,
- `v.reshape(n,m)` : Pour redimensionner un vecteur de taille n,m
- `np.eye(n)` : Pour créer une matrice identité de taille n,
- `np.nonzero(v)` : Pour trouver les indices des valeurs non nulles deu vecteur v,
- `v.mean()` : Pour obtenir la moyenne d'un vecteur,
- `np.unique(v)` : Pour obtenir la liste des valeurs uniques d'une matrice.
- `np.flip(v)` : Pour inverser un vecteur v.

Où i, n, m et k sont des valeurs numériques entières.

**Q1**. Importez la librairie numpy

**Q2**. Créez un vecteur de taille 10 contenant que des 0, la cinquième valeur doit être 1. Les valeurs du tableau doivent être des `int`.

In [ ]:
v1 = 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**Q3**. Créez deux vecteurs aléatoires de taille 5, puis multipliez les vecteurs entre-eux.

In [ ]:
v2 = 

array([6, 2, 5, 8, 0])

In [ ]:
v3 = 

array([1, 6, 8, 6, 3])

array([ 6, 12, 40, 48,  0])

**Q4**. Créez un vecteur avec des valeurs de 10 à 49 puis inversez l'ordre.

In [ ]:
v4 = 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
v4 = 

In [ ]:
v4

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**Q5**. Créez un vecteur aléatoire de taille 10 et remplacez la valeur maximale par 0.

In [ ]:
v5 = 

array([59, 43, 32, 60, 78, 98, 14, 37, 27, 21])

5

In [ ]:
v5

array([59, 43, 32, 60, 78,  0, 14, 37, 27, 21])

**Q6**. Créez une matrice de taille 3x3 avec des valeurs allant de 0 à 8 inclus.

In [ ]:
v6 =

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
v6 = 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
v6.shape

(3, 3)

**Q7**. Créez une matrice d'identité 3x3.

In [ ]:
v7 = 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Q8**. Créez une matrice de taille 30 avec des valeurs entières aléatoires de 0 à 5 inclus.
- Trouvez ensuite les indices d'éléments non nuls.

In [ ]:
v8 = 

array([2, 4, 0, 1, 4, 2, 2, 0, 5, 2, 0, 0, 4, 0, 3, 1, 0, 3, 1, 0, 0, 0,
       0, 2, 5, 0, 0, 5, 3, 4])

(array([ 0,  1,  3,  4,  5,  6,  8,  9, 12, 14, 15, 17, 18, 23, 24, 27, 28,
        29]),)

**Q9**. Créez une matrice 10x10 avec des valeurs aléatoires et trouvez les valeurs minimales et maximales.

In [ ]:
v9 = 

array([[ 5, 48,  1, 40,  3, 41,  6, 27, 18, 20],
       [ 8,  4,  8, 13, 10,  9, 42,  4, 10, 48],
       [16, 33, 10, 10, 35, 38, 24, 23, 16, 18],
       [22, 49,  7, 30, 23, 27, 40, 18,  0, 27],
       [10, 39, 12, 28, 29, 40, 10,  1, 35, 20],
       [36, 23, 13,  5, 18, 36, 38,  7,  3, 20],
       [34, 36, 39,  5,  5, 13, 40,  0,  4,  7],
       [28,  8,  4, 39, 36, 11, 38, 15, 48, 49],
       [27, 13, 16, 33,  0, 25, 31, 23, 37,  4],
       [40,  8, 14,  5, 15, 18, 39, 16, 28, 37]])

**Q10**. Soustrayez la moyenne de chaque ligne d'une matrice aléatoire de taille 5x10.

In [ ]:
v10 = 


array([[67, 15,  8, 80, 74, 51, 87, 10, 47, 28],
       [80, 48, 91, 72, 94, 68,  7, 91, 36, 38],
       [93,  1, 85, 94,  8, 25, 64, 81, 37, 79],
       [ 2, 95,  0, 36, 28, 11,  8, 91, 22, 41],
       [92, 44,  7, 21, 43, 63, 52, 99, 34, 73]])

array([[46.7],
       [62.5],
       [56.7],
       [33.4],
       [52.8]])

array([[ 14.4,   9.4, -14.6,  24.4,   4.4, -15.6, -12.6,  -6.6,  11.4,
        -14.6],
       [  5.4, -20.6,  -9.6,   0.4,  12.4,   9.4,  14.4, -21.6,  22.4,
        -12.6],
       [ 10.8, -10.2, -15.2,   3.8,  10.8, -11.2,  -9.2,   4.8,  -5.2,
         20.8],
       [ 21.7,   1.7,  -3.3, -22.3,  15.7,  18.7,  -4.3, -17.3,  14.7,
        -25.3],
       [ 16. ,   6. ,  18. , -10. ,  -2. ,   9. , -13. ,  -8. ,   2. ,
        -18. ]])

**Q11 BONUS**. Ecrivez une fonction qui trouve la valeur la plus fréquente dans un tableau.

**Q12BONUS**. Créez une matrice 10x10 avec la valeur 1 sur les bordures et 0 à l'intérieur.

**Q13BONUS**. Créez une matrice m3 de taille 8x8 puis remplissez-la avec un motif en damier (0,1).

**Q14BONUS**. Créez un vecteur v5 rempli de 30 valeurs entières aléatoires entre 1 et 10. Transformez en négatif les éléments qui sont entre 3 et 8.