# **Jour 3 —  Librairie - NumPy**


![](https://images.unsplash.com/photo-1476525223214-c31ff100e1ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80)
Picture by [Jason Briscoe](https://unsplash.com/photos/HN_4K2diUWs)

Il s'agit d'un exercice où vous devrez passer un peu de temps à explorer la documentation de [NumPy documentation](https://numpy.org/doc/1.18/).

Pour installer numpy utilisez la commande suivante dans votre terminal :
`pip install numpy`

Sur macOS :
`pip3 install numpy`



Pour vous aider à réaliser ce TD, consultez et utilisez les fonctions suivantes :
- `import numpy as np`  : Pour importer la biblothèque numpy,
- `np.array([i1,i2,i3])` : Pour créer un vecteur contenant les éléments i1, i2 et i3,
- `np.zeros(n)`  : Pour créer un vecteur de taille n contenant que des 0,
- `v[i]` : Pour obtenir la valeur à l'index i du vecteur v,
- `np.random.randint(n, m, k)` : Pour créer des vecteurs de taille k ayant des valeurs aléatoires comprises entre n à m,
- `np.arange(n,m)`  :  Pour créer des vecteurs ayant des valeurs de n à m,
- `v.argmax()` : Pour trouver l'indice de la valeur maximale,
- `v[i]` : Pour obtenir la valeur à l'index i du vecteur v,
- `np.nonzero(n)`  : Pour créer des vecteurs de taille n,
- `v.reshape(n,m)` : Pour redimensionner un vecteur de taille n,m
- `np.eye(n)` : Pour créer une matrice identité de taille n,
- `np.nonzero(v)` : Pour trouver les indices des valeurs non nulles deu vecteur v,
- `v.mean()` : Pour obtenir la moyenne d'un vecteur,
- `np.unique(v)` : Pour obtenir la liste des valeurs uniques d'une matrice.
- `np.flip(v)` : Pour inverser un vecteur v.

Où i, n, m et k sont des valeurs numériques entières.

In [1]:
[1, 2, 3] + [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 683.2 kB/s eta 0:00:18
   - -------------------------------------- 0.5/12.8 MB 683.2 kB/s eta 0:00:18
   - -------------------------------------- 0.5/12.8 MB 683.2 kB/s eta 0:00:18
   -- ------------------------------------- 0.8/12.8 MB 494.3 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/12.8 MB 494.3 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/12.8 MB 494.3 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/12.8 MB 494.3 kB/s eta 0:00:25
   --- ------------------------------------ 1.0/12.8 MB 439.9 kB/s eta 0:00:27
   --- ------------------------------------ 1.0/12.8 MB 439.9 kB/s eta 0:00:27
   --- ------------------------------------ 1.0/12.8 MB 439.9 kB/s eta 0:00:27



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


**Q1**. Importez la librairie numpy

In [5]:
import numpy as np

In [7]:
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])

In [8]:
array1 + array2

array([2, 4, 6])

In [9]:
array1.sum()

np.int64(6)

In [10]:
array1.mean()

np.float64(2.0)

In [12]:
array1 * 5

array([ 5, 10, 15])

In [16]:
array1 / array2

array([1., 1., 1.])

In [18]:
array1 / np.array([1, 2, 0]) 

C:\Users\Quera\AppData\Local\Temp\ipykernel_34744\2567181180.py:1: RuntimeWarning: divide by zero encountered in divide
  array1 / np.array([1, 2, 0])


array([ 1.,  1., inf])

**Q2**. Créez un vecteur de taille 10 contenant que des 0, la cinquième valeur doit être 1. Les valeurs du tableau doivent être des `int`.

In [20]:
v1 = np.zeros(10, int)
v1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
v1[4] =1
v1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

**Q3**. Créez deux vecteurs aléatoires de taille 5, puis multipliez les vecteurs entre-eux.

In [26]:
v2 = np.random.randint(0, 10, 5)
v2

array([7, 0, 9, 3, 0], dtype=int32)

In [27]:
v3 = np.random.randint(0, 10, 5)

In [29]:
v2 * v3

array([49,  0, 36,  6,  0], dtype=int32)

In [34]:
v2[0]

np.int32(7)

**Q4**. Créez un vecteur avec des valeurs de 10 à 49 puis inversez l'ordre.

In [36]:
v4 = np.arange(10, 50)
v4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [37]:
v4[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [38]:
np.flip(v4)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**Q5**. Créez un vecteur aléatoire de taille 10 et remplacez la valeur maximale par 0.

In [40]:
v5 = np.random.randint(0, 100, 10)
v5

array([57, 38, 33, 80, 41, 18, 79, 71, 12, 93], dtype=int32)

In [43]:
v5[v5.argmax()] = 0
v5

array([57, 38, 33, 80, 41, 18, 79, 71, 12,  0], dtype=int32)

**Q6**. Créez une matrice de taille 3x3 avec des valeurs allant de 0 à 8 inclus.

In [44]:
v6 = np.arange(9)
v6

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
v6 = v6.reshape(3, 3)
v6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
v6.shape

(3, 3)

**Q7**. Créez une matrice d'identité 3x3.

In [49]:
v7 = np.eye(3)
v7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Q8**. Créez une matrice de taille 30 avec des valeurs entières aléatoires de 0 à 5 inclus.
- Trouvez ensuite les indices d'éléments non nuls.

In [54]:
v8 = np.random.randint(0, 6, 30)
v8

array([0, 2, 5, 5, 0, 0, 4, 2, 2, 2, 0, 1, 1, 1, 1, 4, 2, 2, 4, 3, 2, 1,
       4, 4, 0, 2, 1, 5, 2, 4], dtype=int32)

In [57]:
np.nonzero(v8)

(array([ 1,  2,  3,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 25, 26, 27, 28, 29]),)

In [56]:
v8[np.nonzero(v8)]

array([2, 5, 5, 4, 2, 2, 2, 1, 1, 1, 1, 4, 2, 2, 4, 3, 2, 1, 4, 4, 2, 1,
       5, 2, 4], dtype=int32)

In [62]:
v8 == 5

array([False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False])

In [60]:
#Filtre
v8[v8 == 5]

array([5, 5, 5], dtype=int32)

In [ ]:
#Filtre
v8[v8 > 2]

array([5, 5, 4, 4, 4, 3, 4, 4, 5, 4], dtype=int32)

**Q9**. Créez une matrice 10x10 avec des valeurs aléatoires et trouvez les valeurs minimales et maximales.

In [68]:
v9 = np.random.randint(0, 100, (10, 10))
v9

array([[90, 53, 77, 54, 44, 26, 69, 90, 88, 71],
       [54, 65, 90, 78, 84,  2, 34, 86, 29, 15],
       [15, 28, 48, 81, 91, 65, 49,  4, 58, 24],
       [98, 48, 64, 65, 62, 86, 48, 65, 71, 92],
       [66, 68,  5, 52,  8, 44, 88, 61, 22, 98],
       [44, 11,  7, 10, 39, 93, 43, 76, 80, 58],
       [75, 46, 48, 78, 51, 13, 53, 37, 75, 48],
       [69, 16,  9, 30, 39, 81, 27, 88, 91,  9],
       [73, 72, 24, 98, 45,  6, 67, 29, 17, 82],
       [46, 61,  6, 20, 15, 72, 61, 87, 55, 71]], dtype=int32)

In [69]:
v9.max()

np.int32(98)

In [70]:
v9.min()

np.int32(2)

**Q10**. Soustrayez la moyenne de chaque ligne d'une matrice aléatoire de taille 5x10.

In [72]:
v10 = np.random.randint(0, 100, (5, 10))
v10


array([[24, 53, 39, 57,  4, 90, 33,  8, 69, 24],
       [ 4, 45, 86, 28,  1,  6, 31, 42, 59, 27],
       [29, 29,  0, 72, 41, 39, 69, 97, 78, 99],
       [23, 98,  2, 17, 11, 60, 23, 89, 22, 90],
       [12, 91, 57, 12, 20, 27, 97, 72, 89, 97]], dtype=int32)

In [82]:
v10.mean(axis=1, keepdims=True)

array([[40.1],
       [32.9],
       [55.3],
       [43.5],
       [57.4]])

In [80]:
v10 - v10.mean(axis=1, keepdims=True)

array([[-16.1,  12.9,  -1.1,  16.9, -36.1,  49.9,  -7.1, -32.1,  28.9,
        -16.1],
       [-28.9,  12.1,  53.1,  -4.9, -31.9, -26.9,  -1.9,   9.1,  26.1,
         -5.9],
       [-26.3, -26.3, -55.3,  16.7, -14.3, -16.3,  13.7,  41.7,  22.7,
         43.7],
       [-20.5,  54.5, -41.5, -26.5, -32.5,  16.5, -20.5,  45.5, -21.5,
         46.5],
       [-45.4,  33.6,  -0.4, -45.4, -37.4, -30.4,  39.6,  14.6,  31.6,
         39.6]])

**Q11 BONUS**. Ecrivez une fonction qui trouve la valeur la plus fréquente dans un tableau.

**Q12BONUS**. Créez une matrice 10x10 avec la valeur 1 sur les bordures et 0 à l'intérieur.

**Q13BONUS**. Créez une matrice m3 de taille 8x8 puis remplissez-la avec un motif en damier (0,1).

**Q14BONUS**. Créez un vecteur v5 rempli de 30 valeurs entières aléatoires entre 1 et 10. Transformez en négatif les éléments qui sont entre 3 et 8.